### ISSUE TITLE
Laravel 5: dev-master and minimum stability setting

### ISSUE THREAD

**Issue by skecskes** [industrious-mouse/laravel-dotmailer#2]
Hi,

As I can see, v0.1.0 is for Laravel 4.2. My current project use L5 and after requiring dev-master:

```
composer require "industrious-mouse/laravel-dotmailer": "dev-master"
```

I received this error:

```
[InvalidArgumentException]                                                                                                                  
Could not find package dev-master at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability  
```

The workaround for this error for now is:

```
composer require "industrious-mouse/laravel-dotmailer": "dev-master as 0.2.0"
```

Do you know what is causing that error message?

**Comment by christian-thomas** [comment]
Hi,

I've just updated this for L5 — If you have a look at the readme again, you'll just need to follow the Installation section for L5.

**Comment by skecskes** [comment]
excellent, thanks
