### ISSUE TITLE
Vendor:publish giving error

### ISSUE THREAD

**Issue by imperium2335** [industrious-mouse/laravel-dotmailer#4]
If I do:

php artisan vendor:publish --provider="IndustriousMouse\LaravelDotmailer\LaravelDotmailerServiceProvider"

I get:

{"error":{"type":"ErrorException","message":"Undefined index: username","file":"
C:\wamp\vhosts\view\laravel\vendor\industrious-mouse\laravel-dotmailer\s
rc\LaravelDotmailerServiceProvider.php","line":34}}

I am using Laravel 4.

If I try to use a page in my app it tells me that the $config['username'] is not defined:

```
    $credentials = [
        Container::USERNAME         => $config['username'],
        Container::PASSWORD         => $config['password']
    ];
```

**Comment by christian-thomas** [comment]
The package is for Laravel 5 I'm afraid, and not maintained.

[Version 0.1](https://github.com/industrious-mouse/laravel-dotmailer/tree/0.1) was for Laravel 4, so you might have better look with that one.
