### ISSUE TITLE
Class not found

### ISSUE THREAD

**Issue by rudolphp** [industrious-mouse/laravel-dotmailer#5]
Hi I get the error "Class 'App\Jobs\ApiContact' not found"

I am trying to use this in Laravel after following the steps provided in README.

**Do I need to give a path in "use" to use this lib. It is not specified in the Doc.**

 $contact_data = new ApiContact([
            'email'         => $this->user->email,
            'emailType'     => 'Html',
            'dataFields'    => [
                    [
                        'key' => 'Title',
                        'value' => $this->user->tname
                    ],
               ]);

```
        try
        {
            $contact = Dotmailer::PostContacts($contact_data);
        }
```

**Comment by rudolphp** [comment]
I included use DotMailer\Api\DataTypes\ApiContact;
Now the error is "Cannot use 'Null' as class name as it is reserved"
This is because if the class Null.php in DotMailer\Api\DataTypes

**Comment by christian-thomas** [comment]
@rudolphp The package is not maintained I'm afraid.

The issue you mention relates to PHP7 and [an issue in the underlying package](https://github.com/romanpitak/dotMailer-API-v2-PHP-client/issues/22), the package I've provided is just a wrapper.
